### ISSUE TITLE
document is not supporting inside JS function which called by isolate_worker

### ISSUE THREAD

**Issue by deepbhavsar** [iandis/isolated_worker#7]
I am creating the element using the `document.createElement('input')` inside the JS function. I am calling that function using the `JsIsolatedWorker().run(functionName: 'alertMessage',arguments: '100')` It is giving me error: 

This is my JS function. I am getting image using input type=file. Plan is to return file path from this function.

```
async function createDynamicInput() {
var input = document.createElement('input');
input.type = 'file';
input.onchange = e => {
   var file = e.taralertMessageget.files[0];
   console.log(file);
   return file;
}
input.click();
}
```
Calling this function using:

```
var result = await JsIsolatedWorker().run(
        functionName: 'createDynamicInput',
        arguments: '100',
      );
      print("==$result");

```

Error: ReferenceError: document is not defined.

Let me know the correct way or require to make changes into current code. Thanks

**Comment by iandis** [comment]
Hi, have you imported the script file using `JsIsolatedWorker.importScripts` first before running the function?

Edit:
The main problem actually comes from calling the `document` since it's not available on Web Workers. [reference](https://www.w3schools.com/html/html5_webworkers.asp#:~:text=Web%20Workers%20and%20the%20DOM,to%20the%20following%20JavaScript%20objects%3A&text=The%20document%20object)

**Comment by iandis** [comment]
Closing this as this is not the package's issue itself.
